import 'package:iconify_flutter/icons/maki.dart';

import '../model/rendered_map_feature.dart';

class MapIconCatalog {
  const MapIconCatalog._();

  static const styleIcons = <String, String>{
    'omt-aerialway': Maki.aerialway_15,
    'omt-airport': Maki.airport_15,
    'omt-alcohol-shop': Maki.alcohol_shop_15,
    'omt-art-gallery': Maki.art_gallery_15,
    'omt-attraction': Maki.attraction_15,
    'omt-bank': Maki.bank_15,
    'omt-bar': Maki.bar_15,
    'omt-beer': Maki.beer_15,
    'omt-bicycle': Maki.bicycle_15,
    'omt-bus': Maki.bus_15,
    'omt-cafe': Maki.cafe_15,
    'omt-campsite': Maki.campsite_15,
    'omt-car': Maki.car_15,
    'omt-castle': Maki.castle_15,
    'omt-cemetery': Maki.cemetery_15,
    'omt-circle': Maki.circle_15,
    'omt-college': Maki.college_15,
    'omt-dog-park': Maki.dog_park_15,
    'omt-drinking-water': Maki.drinking_water_15,
    'omt-entrance': Maki.entrance_15,
    'omt-fast-food': Maki.fast_food_15,
    'omt-fitness': Maki.fitness_centre_15,
    'omt-fuel': Maki.fuel_15,
    'omt-golf': Maki.golf_15,
    'omt-grocery': Maki.grocery_15,
    'omt-harbor': Maki.harbor_15,
    'omt-home': Maki.home_15,
    'omt-hospital': Maki.hospital_15,
    'omt-laundry': Maki.laundry_15,
    'omt-library': Maki.library_15,
    'omt-lodging': Maki.lodging_15,
    'omt-marker': Maki.marker_15,
    'omt-mountain': Maki.mountain_15,
    'omt-music': Maki.music_15,
    'omt-office': Maki.commercial_15,
    'omt-park': Maki.park_15,
    'omt-parking': Maki.parking_15,
    'omt-picnic-site': Maki.picnic_site_15,
    'omt-pitch': Maki.pitch_15,
    'omt-playground': Maki.playground_15,
    'omt-post': Maki.post_15,
    'omt-rail': Maki.rail_15,
    'omt-recycling': Maki.recycling_15,
    'omt-restaurant': Maki.restaurant_15,
    'omt-school': Maki.school_15,
    'omt-shelter': Maki.shelter_15,
    'omt-shop': Maki.shop_15,
    'omt-stadium': Maki.stadium_15,
    'omt-swimming': Maki.swimming_15,
    'omt-toilet': Maki.toilet_15,
    'omt-town-hall': Maki.town_hall_15,
    'omt-village': Maki.village_15,
    'omt-waste-basket': Maki.waste_basket_15,
    'omt-water': Maki.water_15,
  };

  static String iconImageForFeature(RenderedMapFeature feature) {
    final subclass = feature.properties['subclass'];
    final objectClass = feature.properties['class'];
    return switch (subclass) {
      'playground' => 'omt-playground',
      'recycling' => 'omt-recycling',
      'waste_basket' => 'omt-waste-basket',
      'post_box' => 'omt-post',
      'bicycle_parking' => 'omt-bicycle',
      'parking' => 'omt-parking',
      'toilets' => 'omt-toilet',
      'drinking_water' => 'omt-drinking-water',
      'shelter' => 'omt-shelter',
      'picnic_site' || 'picnic_table' => 'omt-picnic-site',
      'camp_site' || 'campsite' => 'omt-campsite',
      'dog_park' => 'omt-dog-park',
      'fitness_station' || 'fitness_centre' => 'omt-fitness',
      'bollard' => 'omt-circle',
      _ => switch (objectClass) {
        'shop' => 'omt-shop',
        'office' => 'omt-office',
        'town_hall' => 'omt-town-hall',
        'fast_food' => 'omt-fast-food',
        'bus' => 'omt-bus',
        'railway' => 'omt-rail',
        'aerialway' => 'omt-aerialway',
        'laundry' => 'omt-laundry',
        'grocery' => 'omt-grocery',
        'library' => 'omt-library',
        'college' => 'omt-college',
        'lodging' => 'omt-lodging',
        'ice_cream' || 'cafe' => 'omt-cafe',
        'post' => 'omt-post',
        'school' => 'omt-school',
        'alcohol_shop' => 'omt-alcohol-shop',
        'bar' => 'omt-bar',
        'harbor' => 'omt-harbor',
        'car' => 'omt-car',
        'hospital' => 'omt-hospital',
        'cemetery' => 'omt-cemetery',
        'attraction' => 'omt-attraction',
        'beer' => 'omt-beer',
        'music' => 'omt-music',
        'stadium' => 'omt-stadium',
        'art_gallery' => 'omt-art-gallery',
        'clothing_store' => 'omt-shop',
        'swimming' => 'omt-swimming',
        'castle' => 'omt-castle',
        'atm' => 'omt-bank',
        'fuel' => 'omt-fuel',
        'bollard' => 'omt-circle',
        _ => 'omt-circle',
      },
    };
  }
}
